### PR TITLE
Added Readme file

### PR DESCRIPTION
**Pull request by ananyag309**
issue #134 
@chirantanbanik sir please check and tell me what more you want me to add, is it looking fine or i need to change something.

### CODE REVIEW

**Comment by chirantanbanik** [comment]
@ananyag309 The **README.md** looks great but there needs to be some changes. Ping me up at @chirantanbanik on discord where I will tell where to make the changes.

**Comment by ananyag309** [comment]
@chirantanbanik i couldn't find your discord profile

**Comment by ananyag309** [comment]
@chirantanbanik sir you just merged my pull req. Please add gssoc and level label along with my name in assignes - it's necesaary for points. Thank you

**Comment by chirantanbanik** [comment]
Yes @ananyag309 I know I will but before that the change you need to make is in Tech Stack section you need to remove CSS, Nodejs and MongoDB logo and add Tailwind CSS, Appwrite and Vercel logo as we have used this at Wellread instead of the logo you have mentioned.

**Comment by ananyag309** [comment]
ok sure i will make the required changes soon

**Pull request merged**
