### PR TITLE
added react-hot-toast on posting

### LINKED ISSUE #125: 💡[Feature]:  we can add beautiful toast message when user add post
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@chirantanbanik 

we can add `react hot toast` for beautiful toast messsage
when user add post, remove post we can display it

### Use Case

it help to provide better user experience

### Benefits

it help user for better ui

### Add ScreenShots

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by dhruv8433**
@chirantanbanik 

## 💡[Feature]: we can add beautiful toast message when user add post #125
close #125

added react-hot-toast 
when user add post  one beautiful toast messaage display on the top

### CODE REVIEW

**Comment by dhruv8433** [comment]
@chirantanbanik 

please add `level` label

**Comment by dhruv8433** [comment]
@chirantanbanik 

kindly please add `level` label in this pr

**Comment by dhruv8433** [comment]
@chirantanbanik 

please add level lable !!!

**Comment by chirantanbanik** [comment]
Have patience @dhruv8433 I know I have to add label, you have worked hard so I will add label. You should know that one can be busy with a lot things going on.

**Pull request merged**
