### PR TITLE
make add post form resopnsive

### LINKED ISSUE #96: [Bug] : Add Post is not responsive
**Describe the bug**
@chirantanbanik 

check this out,
add post is not responsive

**To Reproduce**
1. Go to `add post` route
2. cehck in responsive

**Expected behavior**
- we must use grid layout so it can be responsive

**Screenshots**

image

**Smartphone (please complete the following information):**
 - Device: `samsung A51/71`

**Additional context**

### PR DESCRIPTION
**Pull request by dhruv8433**
### description: 
@chirantanbanik 

[Bug] : Add Post is not responsive #96

close #96 

### screenshorts

image

image

### CODE REVIEW

**Comment by dhruv8433** [comment]
@chirantanbanik 

kindlly please check this and merge it

**Comment by chirantanbanik** [comment]
@dhruv8433 As the Logout button is overflowing, fit it inside the navbar.

**Comment by dhruv8433** [comment]
@chirantanbanik 

i will do it in  #94
i create navigation responsive for all pages

**Comment by dhruv8433** [comment]
@chirantanbanik 

Please merge this so i can work on responsive design

**Comment by chirantanbanik** [comment]
You need to create a new PR after fitting the Logout inside the navbar.

**Comment by dhruv8433** [comment]
Okk got it

**Comment by dhruv8433** [comment]
@chirantanbanik 

can you please add `level 2` in this
i added burger menu and add some `transaction` animation

image

**Comment by dhruv8433** [comment]
@chirantanbanik 

kindly please check this and merge it

**Pull request closed without merging**
