### PR TITLE
Made new Login and Sign Up page

### PR DESCRIPTION
**Pull request by IbrahimDev00**
### Login page: 

1. Added a new attractive background gradient.
2. Added a quote for the "WellRead" site.
3. Added better error handling and error messages.
4. Added interactivity to the button.
5. Added interactivity to the input fields.
6. Made the "Login" text more visible.
7. Put the sign up link at the bottom for better UX.

### Sign Up page:

1. Added a new attractive background gradient.
2. Added a quote for the "WellRead" site.
3. Added better error handling and error messages.
4. Added interactivity to the button.
5. Added interactivity to the input fields.
6. Made the "Signup" text more visible.
7. Put the login link at the bottom for better UX.

https://github.com/chirantanbanik/Wellread/assets/147825977/0f5232c7-f2c1-4a1c-a053-d91952df8cb4

### CODE REVIEW

**Comment by chirantanbanik** [comment]
@IbrahimDev00 the design is good but could you use blue/sky blue instead of black?

**Comment by IbrahimDev00** [comment]
> @IbrahimDev00 the design is good but could you use blue/sky blue instead of black?

Sure thing. I'll make those changes and upload a video.

**Comment by IbrahimDev00** [comment]
https://github.com/chirantanbanik/Wellread/assets/147825977/13d76cc1-8ee1-4a2d-bc42-99839642c937

Changed the background to blue.
@chirantanbanik

**Comment by chirantanbanik** [comment]
@IbrahimDev00 The design and not according to the project structure.

**Pull request closed without merging**
