### PR TITLE
Added landing page and framer motion

### PR DESCRIPTION
**Pull request by Lavanyaaa25**
Designed the landing page with animations. 

https://github.com/chirantanbanik/Wellread/assets/114211427/1e216629-37b8-4134-b99b-5780a17357f1

### CODE REVIEW

**Comment by Lavanyaaa25** [comment]
@chirantanbanik Is this fine?

**Comment by chirantanbanik** [comment]
Please remove the testimonials.

**Comment by Lavanyaaa25** [comment]
> Please remove the testimonials.

okay

**Comment by chirantanbanik** [comment]
Hello @Lavanyaaa25 did you remove the testimonials?

**Comment by Lavanyaaa25** [comment]
Yeahh.. There were conflicts.. Will resolve and push it by 4 today. Sorry
for the delay

**Pull request closed without merging**
