### PR TITLE
User profile

### PR DESCRIPTION
**Pull request by AnanyaJain25**
## Description
Testinomials section was having overlaps.

## Related Issue
Make user profile #68
Showing author name on each Post #71
Profile avatar on each Post #72
Adding edit profile feature #73

## Changes
Profile display feature , edit profile feature, clickable avatar which will direct to author's profile, and author name on each post.

## Type of PR

- [] Bug fix
- [x] Feature enhancement

## Testing Instructions
Create new collection in Database named as Profiles.
Create attributes as below
Screenshot 2024-05-31 170724
Once database/collection is configured add new collection id in both .env and conf files.
Also run npm install @mui/material @emotion/react @emotion/styled on terminal (Avatar has been used from MUI library)
Add author attribute in articles collection.
AFTER LOGGING IN PLEASE RELOAD ONCE FOR SMOOTH FUNCTIONING

## Impact Analysis

- [N] Breaking change: This change introduces breaking modifications.
- [Y] Non-breaking change: This change does not introduce breaking modifications.
- [N] Disrupts existing functionality: This change disrupts the functionality of existing features.
- [Y] Does not disrupt existing functionality: This change does not disrupt the functionality of existing features.

## Checklist
- [Y] I have tested the changes locally and they work as expected.
- [Y] I have updated the documentation if necessary.
- [Y] I have reviewed the code and ensured it follows project standards.
- [Y] All tests (if applicable) pass successfully.
- [Y] I have added myself to the list of contributors if this is a significant contribution.

##SCREENSHOTS
Avatars are clickable and author name added.
Screenshot 2024-05-31 174004
will not show edit button if you are viewing somebody else's profile
Screenshot 2024-05-31 174013
will show edit button if you are logged in
Screenshot 2024-05-31 174031

### CODE REVIEW

**Comment by AnanyaJain25** [comment]
@chirantanbanik I have one request Sir adding Avatar took a good amount of time. To navigate to different users profile I had to update rooutes embed userId in routes and then use params for fetching and displaying profile. Also I have used MUI library to have best avatar. Please assign atleast label 2 for this task. I will be grateful.

**Comment by chirantanbanik** [comment]
Hey @AnanyaJain25 did you also pushed the .env file?

**Comment by AnanyaJain25** [comment]
> Hey @AnanyaJain25 did you also pushed the .env file?

No sir

**Comment by chirantanbanik** [comment]
Don't push the .env because when you set the project to your local system using Appwrite then you need to create your own .env to use the project and when you push the .env that you created the everything will start saving in your Appwrite account.

**Comment by AnanyaJain25** [comment]
> Don't push the .env because when you set the project to your local system using Appwrite then you need to create your own .env to use the project and when you push the .env that you created the everything will start saving in your Appwrite account.

Yes Sir but I havent pushed .env . I have mentioned it in gitignore file. It should not be there only .env.example must be visible

**Comment by AnanyaJain25** [comment]
Sir should I raise separate PRs for each feature ? I hope all issues are individually counted for the score!

**Comment by AnanyaJain25** [comment]
> You have added **VITE_APPWRITE_COLLECTION_PROFILES_ID=""** right?

Yes Sir, You will have to add your own Collection Id inside it.

**Comment by chirantanbanik** [comment]
You can ask the doubts @chirantanbanik in the discord it will be better.

**Comment by AnanyaJain25** [comment]
hey @chirantanbanik please review the PR.

**Comment by AnanyaJain25** [comment]
@chirantanbanik plz assign labels to PR

**Comment by AnanyaJain25** [comment]
please assign labels

**Comment by chirantanbanik** [comment]
Have patience @AnanyaJain25 I know I have to add label, you have worked hard so I will add label. You should know that one can be busy with a lot things going on.

**Comment by AnanyaJain25** [comment]
> Have patience @AnanyaJain25 I know I have to add label, you have worked hard so I will add label. You should know that one can be busy with a lot things going on. I have given this PRs label to #83 and you have referred User profile and Author profile to issue 71 so the label is on the Author profile.

You know what mistake i did I made all 4 tasks changes in same branch otherwise you would have understood what all changes have been made for which feature. And now I have been trying to exlain you the same since long ! The 4 tasks are absolutely different. User profile has nothing to do with displaying name on each post! My task under make user profile was to create it! and then under edit profile task was to make it editable. under author name was to display name on post card and under avatar I had to make avatar for posts which are clickable

**Pull request merged**
